### PR TITLE
feat: Reducing time taken when wait_workflow used

### PR DESCRIPTION
**Pull request by Steph0**
* [modified] Avoidable loss of 10sec of runner

The sleep in `trigger_workflow` is a loss of 10 seconds on Github runners (which [cost money](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions)) that can be avoided since `wait_for_workflow_to_finish` will still do the job if user wants to wait for workflow.
**Especially if a user uses `wait_workflow=false` since he specifically asks to not wait.**

Concerned lines:
```shell
echo "Sleeping for $wait_interval seconds"
sleep $wait_interval
```

* [modified] Ash script issues
  * https://github.com/koalaman/shellcheck/wiki/SC2113
  * https://github.com/koalaman/shellcheck/wiki/SC2086
  * https://fr.wikipedia.org/wiki/Shebang
  * https://dev.to/meleu/what-the-shebang-really-does-and-why-it-s-so-important-in-your-shell-scripts-2755
 
* [modified] README.md - applying markdown best practices

### CODE REVIEW

**Comment by Steph0** [comment]
Up @keithconvictional :)

**Review by keithconvictional — COMMENTED** [review]
@Steph0 Thanks for putting this together. Changes look good. Give me 24 hours to test them out.

**Comment by Steph0** [comment]
@keithconvictional my pleasure! :)

**Comment by Steph0** [comment]
@keithconvictional 😞

**Comment by keithconvictional** [comment]
@Steph0 released in v1.4.0. Thanks for contributing!

**Comment by Steph0** [comment]
@keithconvictional thanks to you! Migrating all our apps to 1.4.0 as of today :)

**Comment by NotNils** [comment]
I've tested between v1.3 and v1.4 and v1.3 is more stable because of that first 10 second sleep than v1.4, but I like the feature of v1.5 xD

**Pull request merged**
