### PR TITLE
Add `workflow_id` and `workflow_url` as action outputs

### PR DESCRIPTION
**Pull request by shabih-paystack**
This PR adds 2 outputs to the action. The outputs can be used to navigate to the logs of the workflow triggered by this action.

### CODE REVIEW

**Comment by warsmit** [comment]
Can you add URL link of workflow too? :)

**Comment by yurist38** [comment]
Guys, really need it! Are you gonna merge it?

**Review by keithconvictional — APPROVED** [review]
LGTM

**Comment by keithconvictional** [comment]
@shabih-paystack Thanks for the contribution!

**Comment by keithconvictional** [comment]
This work is in: https://github.com/convictional/trigger-workflow-and-wait/releases/tag/v1.5.0

**Comment by yurist38** [comment]
Cool, thanks guys! ❤️

**Pull request merged**
